### PR TITLE
Fix/nex 778/spanner lib generis search errors

### PR DESCRIPTION
**Pull request by boajer**
https://oat-sa.atlassian.net/browse/NEX-778
Not really related to taoCore itself, but is the must for an installation success. 

_postgresql based instance:_ http://test-lib-search.playground.kitchen.it.taocloud.org:44821/ deployed here ( http://playground.kitchen.it.taocloud.org/?p=test-lib-search_delivery.git;a=summary see details) 

_mysql based instance:_ creation should be fixed as per https://oat-sa.atlassian.net/servicedesk/customer/portal/21/OSD-1161

### CODE REVIEW

**Review by siwane — COMMENTED** [review]
why have u removed aliasing?

**Comment by boajer** [comment]
@siwane, because:
1. that was incompatible with a spanner
2. no-one can recall the reason of introduction and use case 
3. testing showing so far - that is redundant (not fully complete yet)

**Review by siwane — APPROVED** [review]

**Review by mike-ionut-mihai-sandu-tao — APPROVED** [review]
LGTM

**Comment by mike-ionut-mihai-sandu-tao** [comment]
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

**Comment by gabrielfs7** [comment]
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

**Review by gabrielfs7 — APPROVED** [review]
lgtm

**Pull request merged**
